dev:
  ROLLBAR_CLIENT_TOKEN:
  ROLLBAR_SERVER_TOKEN:
  ROLLBAR_ENVIRONMENT: dev
staging:
  ROLLBAR_CLIENT_TOKEN:
  ROLLBAR_SERVER_TOKEN:
  ROLLBAR_ENVIRONMENT: staging
prod:
  ROLLBAR_CLIENT_TOKEN:
  ROLLBAR_SERVER_TOKEN:
  ROLLBAR_ENVIRONMENT: production