dev:
  ROLLBAR_CLIENT_TOKEN: dev
  ROLLBAR_SERVER_TOKEN: dev
  ROLLBAR_ENVIRONMENT: dev
staging:
  ROLLBAR_CLIENT_TOKEN: staging
  ROLLBAR_SERVER_TOKEN: staging
  ROLLBAR_ENVIRONMENT: staging
prod:
  ROLLBAR_CLIENT_TOKEN: production
  ROLLBAR_SERVER_TOKEN: production
  ROLLBAR_ENVIRONMENT: production